# Project information
site_name: Cell segmentation
site_description:  Wrapper code to use the generalist cell/nuclei segmentation package [**Cellpose**]
site_author: Florian MUELLER
site_url: https://github.com/fish-quant/segmentation

# Repository
repo_name: GitHub
repo_url: https://github.com/fish-quant/segmentation.git
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2019 Florian MUELLER'

# Configuration
theme:
  name: 'readthedocs'
  #name: mkdocs
  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  #include_search_page: false
  #search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /img/icons8-eukaryotic-cells-filled-100.png
  logo:
    icon: wb_sunny

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/fish-quant/segmentation

# MD extension
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true

nav:
    - Overview: index.md   # Needed for material theme but not for other
    
    - ImJoy: 
      - Overview: imjoy-overview.md  
      - Installation: imjoy-installation.md
      - FAQ: imjoy-faq.md

    - ImJoy Analysis:
      - Overview: analysis-overview.md
      - General behavior: analysis-general-behavior.md 
      - Data: data.md
      - Preprocessing: analysis-preprocessing.md
      - Segmentation: analysis-segmentation.md

    - Diverse workflows:
      - Overview: workflows-overview.md
      - Split channels: workflows-fiji-split-channels.md
      - Distance to objects: workflows-distance-objects.md
      - Create FQ outline files: workflows-create-fq-outlines.md

    - Advanced:
      - Developers: developer.md
    
    - More:  
      - Licence: licence.md
      - Contact: contact.md

#theme:
#  name: 'material'
